# Generated by Django 4.1.7 on 2023-02-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='procedure',
            fields=[
                ('Code', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'procedure',
            },
        ),
    ]
