# Generated by Django 4.1.7 on 2023-03-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_physician_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='fdo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'fdo',
            },
        ),
    ]
